/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sports/find_main_live_by_upcoming_id/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find main live event by upcoming ID
         * @description Retrieves the main live event associated with a specific upcoming event ID.This endpoint is typically called after the event start time to find the corresponding live event.
         */
        get: operations["findMainLiveByUpcomingId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports/coupon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sportCoupon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sport list
         * @description Returns a list of available sports filtered by match status. Each sport includes associated metadata and is scoped to the provided status, such as live or upcoming events.
         */
        get: operations["listSports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports/{status}/{sport}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get game list
         * @description Returns a list of games for the specified sport and status. The response includes all available events associated with the given sport slug, filtered by match status such as live or upcoming.
         */
        get: operations["getGameList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports/{status}/{sport}/{league}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get game list by league
         * @description Returns a list of games for the specified league within a sport and status.
         *
         *     The response contains all available events associated with the given league slug, including upcoming and live games depending on the provided status.
         */
        get: operations["getLeague"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports/{status}/{sport}/{league}/{game}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get game
         * @description Fetches a single game by its unique slug within a league and sport. This endpoint is commonly used to display detailed game information, including match status and related metadata.
         */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findMainLiveByUpcomingId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upcoming event ID (numeric) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of events for a sport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /**
                         * Format: uuid
                         * @example 6f8a7c3e-1f2a-4d8e-b9a1-9c3b6a2c8f11
                         */
                        requestId: string;
                        data: {
                            sportId: number;
                            leagueId: number;
                            id: number;
                            mainId: number;
                        };
                    };
                };
            };
            /** @description Upcoming event not found or no live event available yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example false
                         * @enum {boolean}
                         */
                        success: false;
                        /** @example NOT_FOUND */
                        error: string;
                        /** @example Resource not found */
                        message: string;
                    };
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        issues: {
                            path: string[];
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    sportCoupon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    Events: {
                        /** @example 668362977 */
                        GameId: number;
                        /** @example 1 */
                        Type: number;
                        /** @example 1.23 */
                        Coef: number;
                        /** @example 0 */
                        Param: number;
                        /** @example null */
                        PV: number | null;
                        /** @example 0 */
                        PlayerId: number;
                        /** @example 1 */
                        Kind: number;
                        /** @example 0 */
                        InstrumentId: number;
                        /** @example 0 */
                        Seconds: number;
                        /** @example 0 */
                        Price: number;
                        /** @example 0 */
                        Expired: number;
                        /**
                         * @default []
                         * @example []
                         */
                        PlayersDuel?: unknown[];
                    }[];
                };
            };
        };
        responses: {
            /** @description List of bet sport coupon */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /**
                         * Format: uuid
                         * @example 6f8a7c3e-1f2a-4d8e-b9a1-9c3b6a2c8f11
                         */
                        requestId: string;
                        data: {
                            /** @example 1.23 */
                            coefficient: number;
                            /** @example 0.3 */
                            minBet: number;
                            /** @example 67 */
                            maxBet: number;
                            items: {
                                /** @example 668362977 */
                                gameId: number;
                                /** @example 0 */
                                gameConstId: number;
                                /** @example W1 */
                                name: string;
                                /** @example 1 */
                                marketId: number;
                                /** @example 1 */
                                outcomeId: number;
                                /** @example 0 */
                                param: number;
                                /** @example 1.23 */
                                coefficient: number;
                                /** @example true */
                                suspended: boolean;
                                /** @example true */
                                finish: boolean;
                                /**
                                 * @example live
                                 * @enum {string}
                                 */
                                gameStatus: "live" | "upcoming";
                                /** @example 0 */
                                isRelation: number;
                                /** @example 0 */
                                timeSec: number;
                                /** @example 0 */
                                timeDirection: number;
                            }[];
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        issues: {
                            path: string[];
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    listSports: {
        parameters: {
            query?: {
                /** @description Response language (en, bn, hi, etc.) */
                locale?: "en" | "bn" | "hi";
            };
            header?: never;
            path: {
                /** @description Filter sports by event status */
                status: "live" | "upcoming";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sports list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /**
                         * Format: uuid
                         * @example 6f8a7c3e-1f2a-4d8e-b9a1-9c3b6a2c8f11
                         */
                        requestId: string;
                        data: {
                            /**
                             * @description Unique sport identifier
                             * @example 1
                             */
                            id: number;
                            /**
                             * @description Sport display name
                             * @example Football
                             */
                            name: string;
                            /**
                             * @description URL-friendly sport identifier
                             * @example football
                             */
                            slug: string;
                            /**
                             * @description Total number of games in the league season
                             * @example 38
                             */
                            gc: number;
                            /**
                             * @description Total number of leagues available for this sport
                             * @example 120
                             */
                            lc: number;
                            countries: {
                                /**
                                 * @description Unique country identifier
                                 * @example 44
                                 */
                                id: number;
                                /**
                                 * @description Country name
                                 * @example England
                                 */
                                name: string;
                                leagues: {
                                    /**
                                     * @description Unique league identifier
                                     * @example 1
                                     */
                                    id: number;
                                    /**
                                     * @description League display name
                                     * @example Premier League
                                     */
                                    name: string;
                                    /**
                                     * @description URL-friendly league identifier
                                     * @example premier-league
                                     */
                                    slug: string;
                                    /**
                                     * @description Total number of games in the league season
                                     * @example 38
                                     */
                                    gc: number;
                                }[];
                            }[];
                        }[];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        issues: {
                            path: string[];
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getGameList: {
        parameters: {
            query?: {
                /** @description Response language (en, bn, hi, etc.) */
                locale?: "en" | "bn" | "hi";
            };
            header?: never;
            path: {
                /** @description Filter sports by event status */
                status: "live" | "upcoming";
                /** @description Unique identifier for the sport (e.g., 'football', 'cricket') */
                sport: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of events for a sport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /**
                         * Format: uuid
                         * @example 6f8a7c3e-1f2a-4d8e-b9a1-9c3b6a2c8f11
                         */
                        requestId: string;
                        data: {
                            /**
                             * @description Match identifier
                             * @example 987654
                             */
                            id: number | null;
                            /**
                             * @description Category identifier
                             * @example 4353456
                             */
                            ci?: number | null;
                            /** @description Match teams (home vs away) */
                            team: {
                                /**
                                 * @description Home team
                                 * @example {
                                 *       "id": 12345,
                                 *       "name": "Manchester United",
                                 *       "slug": "manchester-united",
                                 *       "countryId": 44,
                                 *       "logo": "https://cdn.example.com/teams/manchester-united.png"
                                 *     }
                                 */
                                home: {
                                    /**
                                     * @description Unique team identifier
                                     * @example 12345
                                     */
                                    id: number;
                                    /**
                                     * @description Team display name
                                     * @example Manchester United
                                     */
                                    name: string;
                                    /**
                                     * @description URL-friendly team identifier
                                     * @example manchester-united
                                     */
                                    slug: string;
                                    /**
                                     * @description Country identifier where the team is registered
                                     * @example 44
                                     */
                                    countryId: number;
                                    /**
                                     * @description Team logo URL
                                     * @example https://cdn.example.com/teams/manchester-united.png
                                     */
                                    logo?: string | null;
                                };
                                /**
                                 * @description Away team
                                 * @example {
                                 *       "id": 67890,
                                 *       "name": "Liverpool",
                                 *       "slug": "liverpool",
                                 *       "countryId": 44,
                                 *       "logo": "https://cdn.example.com/teams/liverpool.png"
                                 *     }
                                 */
                                away: {
                                    /**
                                     * @description Unique team identifier
                                     * @example 12345
                                     */
                                    id: number;
                                    /**
                                     * @description Team display name
                                     * @example Manchester United
                                     */
                                    name: string;
                                    /**
                                     * @description URL-friendly team identifier
                                     * @example manchester-united
                                     */
                                    slug: string;
                                    /**
                                     * @description Country identifier where the team is registered
                                     * @example 44
                                     */
                                    countryId: number;
                                    /**
                                     * @description Team logo URL
                                     * @example https://cdn.example.com/teams/manchester-united.png
                                     */
                                    logo?: string | null;
                                };
                            };
                            /**
                             * @description League information
                             * @example {
                             *       "id": 1,
                             *       "name": "Premier League",
                             *       "slug": "premier-league"
                             *     }
                             */
                            league: {
                                /**
                                 * @description Unique league identifier
                                 * @example 1
                                 */
                                id: number;
                                /**
                                 * @description League display name
                                 * @example Premier League
                                 */
                                name: string;
                                /**
                                 * @description URL-friendly league identifier
                                 * @example premier-league
                                 */
                                slug: string;
                            };
                            /**
                             * @description Country information
                             * @example {
                             *       "id": 44,
                             *       "name": "England"
                             *     }
                             */
                            country: {
                                /**
                                 * @description Unique country identifier
                                 * @example 44
                                 */
                                id: number;
                                /**
                                 * @description Country name
                                 * @example England
                                 */
                                name: string;
                            };
                            /**
                             * @description Match status
                             * @example live
                             * @enum {string}
                             */
                            status: "live" | "upcoming";
                            /**
                             * @description Unix timestamp (UTC)
                             * @example 1768651200
                             */
                            startTime: number;
                            /**
                             * @description event count
                             * @example 134
                             */
                            ec: number;
                            sport: {
                                /**
                                 * @description Unique sport identifier
                                 * @example 1
                                 */
                                id: number;
                                /**
                                 * @description Sport display name
                                 * @example Football
                                 */
                                name: string;
                                /**
                                 * @description URL-friendly sport identifier
                                 * @example football
                                 */
                                slug: string;
                            };
                            gameTypeId?: number;
                            period?: number;
                            periodName: string;
                            /**
                             * @description Transformed GE markets
                             * @example [
                             *       {
                             *         "id": 6,
                             *         "name": "Total Goals",
                             *         "gs": 1,
                             *         "outcomes": [
                             *           [
                             *             {
                             *               "id": 83,
                             *               "name": "(2.5) Over",
                             *               "coefficient": 1.9,
                             *               "suspended": false,
                             *               "point": 2.5
                             *             },
                             *             {
                             *               "id": 84,
                             *               "name": "(2.5) Under",
                             *               "coefficient": 1.9,
                             *               "suspended": false,
                             *               "point": 2.5
                             *             }
                             *           ]
                             *         ]
                             *       }
                             *     ]
                             */
                            markets?: {
                                /**
                                 * @description Market id
                                 * @example 6
                                 */
                                id: number;
                                /**
                                 * @description Localized market name
                                 * @example Total Goals
                                 */
                                name: string;
                                /**
                                 * @description Market game status
                                 * @example 1
                                 */
                                gs: number;
                                /**
                                 * @description Grouped outcomes (2D array)
                                 * @example [
                                 *       [
                                 *         {
                                 *           "id": 83,
                                 *           "name": "(2.5) Over",
                                 *           "coefficient": 1.9,
                                 *           "suspended": false,
                                 *           "point": 2.5
                                 *         },
                                 *         {
                                 *           "id": 84,
                                 *           "name": "(2.5) Under",
                                 *           "coefficient": 1.9,
                                 *           "suspended": false,
                                 *           "point": 2.5
                                 *         }
                                 *       ]
                                 *     ]
                                 */
                                outcomes: {
                                    /**
                                     * @description Outcome id
                                     * @example 83
                                     */
                                    id: number;
                                    /**
                                     * @description Localized outcome name
                                     * @example (2.5) Over
                                     */
                                    name: string;
                                    /**
                                     * @description Odds coefficient
                                     * @example 1.9
                                     */
                                    coefficient: number;
                                    /**
                                     * @description Outcome suspended status
                                     * @example false
                                     */
                                    suspended?: boolean;
                                    /**
                                     * @description Handicap / line value
                                     * @example 2.5
                                     */
                                    point?: number;
                                    /** @description Player/participant info (if applicable) */
                                    pl?: {
                                        /**
                                         * @description Player/participant id
                                         * @example 1
                                         */
                                        I: number;
                                        /**
                                         * @description Player/participant name
                                         * @example Player Name
                                         */
                                        N: string;
                                    };
                                }[][];
                            }[];
                            groups?: {
                                id: number;
                                name: string;
                                slug: string;
                            }[];
                            marketType?: {
                                id: number;
                                name: string;
                                count: number;
                                key: string;
                            }[];
                            /** @description Additional match metadata from provider */
                            matchInfo?: {
                                /**
                                 * @description Match venue or location
                                 * @example Old Trafford, Manchester
                                 */
                                location?: string;
                                /**
                                 * @description Tournament stage
                                 * @example Semi Final
                                 */
                                stage?: string;
                                /**
                                 * @description Match format
                                 * @example Regular Time
                                 */
                                format?: string;
                            };
                            /** @description Live scoring context; present only when match is live */
                            scoreContext?: {
                                /**
                                 * @description Current period number
                                 * @example 2
                                 */
                                currentPeriod?: number;
                                /**
                                 * @description Stage live status
                                 * @example LIVE
                                 */
                                stageLiveStatus?: string;
                                /**
                                 * @description Current period string
                                 * @example 2nd Half
                                 */
                                currentPeriodString?: string;
                                /** @description Full score */
                                fullScore?: {
                                    /**
                                     * @description Home team full score
                                     * @example 2
                                     */
                                    home?: number;
                                    /**
                                     * @description Home team full score
                                     * @example 2
                                     */
                                    away?: number;
                                };
                                /**
                                 * @description Additional live match information
                                 * @example Match in progress
                                 */
                                info?: string;
                                /**
                                 * @description Current period (used in cricket)
                                 * @example 1
                                 */
                                period?: number;
                                /**
                                 * @description Scores per period
                                 * @example [
                                 *       {
                                 *         "Key": 1,
                                 *         "Value": {
                                 *           "NF": "1st Half",
                                 *           "S1": 1,
                                 *           "S2": 0
                                 *         }
                                 *       }
                                 *     ]
                                 */
                                periodScores?: {
                                    /**
                                     * @description Period key
                                     * @example 1
                                     */
                                    Key: number;
                                    Value: {
                                        /**
                                         * @description Normalized period label
                                         * @example HT
                                         */
                                        NF: string;
                                        /**
                                         * @description Home score for this period
                                         * @example 1
                                         */
                                        S1?: number;
                                        /**
                                         * @description Away score for this period
                                         * @example 0
                                         */
                                        S2?: number;
                                    };
                                }[];
                                setScore?: unknown;
                                /**
                                 * @description Timeout remaining (seconds)
                                 * @example 60
                                 */
                                timeoutRemaining?: number;
                                /**
                                 * @description Match time elapsed in seconds
                                 * @example 3420
                                 */
                                timeSeconds?: number;
                                /** @description Match statistics */
                                matchStatistics?: {
                                    /**
                                     * @description Statistics group key
                                     * @example 1
                                     */
                                    Key: number;
                                    Value: {
                                        /**
                                         * @description Statistic identifier
                                         * @example 101
                                         */
                                        ID: number;
                                        /**
                                         * @description Statistic name
                                         * @example Possession
                                         */
                                        N: string;
                                        /**
                                         * @description Home team value
                                         * @example 55%
                                         */
                                        S1: string;
                                        /**
                                         * @description Away team value
                                         * @example 45%
                                         */
                                        S2: string;
                                    }[];
                                }[];
                            };
                            /**
                             * @description SEO-friendly match slug
                             * @example manchester-united-vs-liverpool
                             */
                            slug: string;
                        }[];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        issues: {
                            path: string[];
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getLeague: {
        parameters: {
            query?: {
                /** @description Response language (en, bn, hi, etc.) */
                locale?: "en" | "bn" | "hi";
            };
            header?: never;
            path: {
                /** @description Filter sports by event status */
                status: "live" | "upcoming";
                /** @description Unique identifier for the sport (e.g., 'football', 'cricket') */
                sport: string;
                /** @description Unique identifier for the league (e.g., '2796379-indonesia-liga-4') */
                league: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of events for a league */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /**
                         * Format: uuid
                         * @example 6f8a7c3e-1f2a-4d8e-b9a1-9c3b6a2c8f11
                         */
                        requestId: string;
                        data: {
                            /**
                             * @description Match identifier
                             * @example 987654
                             */
                            id: number | null;
                            /**
                             * @description Category identifier
                             * @example 4353456
                             */
                            ci?: number | null;
                            /** @description Match teams (home vs away) */
                            team: {
                                /**
                                 * @description Home team
                                 * @example {
                                 *       "id": 12345,
                                 *       "name": "Manchester United",
                                 *       "slug": "manchester-united",
                                 *       "countryId": 44,
                                 *       "logo": "https://cdn.example.com/teams/manchester-united.png"
                                 *     }
                                 */
                                home: {
                                    /**
                                     * @description Unique team identifier
                                     * @example 12345
                                     */
                                    id: number;
                                    /**
                                     * @description Team display name
                                     * @example Manchester United
                                     */
                                    name: string;
                                    /**
                                     * @description URL-friendly team identifier
                                     * @example manchester-united
                                     */
                                    slug: string;
                                    /**
                                     * @description Country identifier where the team is registered
                                     * @example 44
                                     */
                                    countryId: number;
                                    /**
                                     * @description Team logo URL
                                     * @example https://cdn.example.com/teams/manchester-united.png
                                     */
                                    logo?: string | null;
                                };
                                /**
                                 * @description Away team
                                 * @example {
                                 *       "id": 67890,
                                 *       "name": "Liverpool",
                                 *       "slug": "liverpool",
                                 *       "countryId": 44,
                                 *       "logo": "https://cdn.example.com/teams/liverpool.png"
                                 *     }
                                 */
                                away: {
                                    /**
                                     * @description Unique team identifier
                                     * @example 12345
                                     */
                                    id: number;
                                    /**
                                     * @description Team display name
                                     * @example Manchester United
                                     */
                                    name: string;
                                    /**
                                     * @description URL-friendly team identifier
                                     * @example manchester-united
                                     */
                                    slug: string;
                                    /**
                                     * @description Country identifier where the team is registered
                                     * @example 44
                                     */
                                    countryId: number;
                                    /**
                                     * @description Team logo URL
                                     * @example https://cdn.example.com/teams/manchester-united.png
                                     */
                                    logo?: string | null;
                                };
                            };
                            /**
                             * @description League information
                             * @example {
                             *       "id": 1,
                             *       "name": "Premier League",
                             *       "slug": "premier-league"
                             *     }
                             */
                            league: {
                                /**
                                 * @description Unique league identifier
                                 * @example 1
                                 */
                                id: number;
                                /**
                                 * @description League display name
                                 * @example Premier League
                                 */
                                name: string;
                                /**
                                 * @description URL-friendly league identifier
                                 * @example premier-league
                                 */
                                slug: string;
                            };
                            /**
                             * @description Country information
                             * @example {
                             *       "id": 44,
                             *       "name": "England"
                             *     }
                             */
                            country: {
                                /**
                                 * @description Unique country identifier
                                 * @example 44
                                 */
                                id: number;
                                /**
                                 * @description Country name
                                 * @example England
                                 */
                                name: string;
                            };
                            /**
                             * @description Match status
                             * @example live
                             * @enum {string}
                             */
                            status: "live" | "upcoming";
                            /**
                             * @description Unix timestamp (UTC)
                             * @example 1768651200
                             */
                            startTime: number;
                            /**
                             * @description event count
                             * @example 134
                             */
                            ec: number;
                            sport: {
                                /**
                                 * @description Unique sport identifier
                                 * @example 1
                                 */
                                id: number;
                                /**
                                 * @description Sport display name
                                 * @example Football
                                 */
                                name: string;
                                /**
                                 * @description URL-friendly sport identifier
                                 * @example football
                                 */
                                slug: string;
                            };
                            gameTypeId?: number;
                            period?: number;
                            periodName: string;
                            /**
                             * @description Transformed GE markets
                             * @example [
                             *       {
                             *         "id": 6,
                             *         "name": "Total Goals",
                             *         "gs": 1,
                             *         "outcomes": [
                             *           [
                             *             {
                             *               "id": 83,
                             *               "name": "(2.5) Over",
                             *               "coefficient": 1.9,
                             *               "suspended": false,
                             *               "point": 2.5
                             *             },
                             *             {
                             *               "id": 84,
                             *               "name": "(2.5) Under",
                             *               "coefficient": 1.9,
                             *               "suspended": false,
                             *               "point": 2.5
                             *             }
                             *           ]
                             *         ]
                             *       }
                             *     ]
                             */
                            markets?: {
                                /**
                                 * @description Market id
                                 * @example 6
                                 */
                                id: number;
                                /**
                                 * @description Localized market name
                                 * @example Total Goals
                                 */
                                name: string;
                                /**
                                 * @description Market game status
                                 * @example 1
                                 */
                                gs: number;
                                /**
                                 * @description Grouped outcomes (2D array)
                                 * @example [
                                 *       [
                                 *         {
                                 *           "id": 83,
                                 *           "name": "(2.5) Over",
                                 *           "coefficient": 1.9,
                                 *           "suspended": false,
                                 *           "point": 2.5
                                 *         },
                                 *         {
                                 *           "id": 84,
                                 *           "name": "(2.5) Under",
                                 *           "coefficient": 1.9,
                                 *           "suspended": false,
                                 *           "point": 2.5
                                 *         }
                                 *       ]
                                 *     ]
                                 */
                                outcomes: {
                                    /**
                                     * @description Outcome id
                                     * @example 83
                                     */
                                    id: number;
                                    /**
                                     * @description Localized outcome name
                                     * @example (2.5) Over
                                     */
                                    name: string;
                                    /**
                                     * @description Odds coefficient
                                     * @example 1.9
                                     */
                                    coefficient: number;
                                    /**
                                     * @description Outcome suspended status
                                     * @example false
                                     */
                                    suspended?: boolean;
                                    /**
                                     * @description Handicap / line value
                                     * @example 2.5
                                     */
                                    point?: number;
                                    /** @description Player/participant info (if applicable) */
                                    pl?: {
                                        /**
                                         * @description Player/participant id
                                         * @example 1
                                         */
                                        I: number;
                                        /**
                                         * @description Player/participant name
                                         * @example Player Name
                                         */
                                        N: string;
                                    };
                                }[][];
                            }[];
                            groups?: {
                                id: number;
                                name: string;
                                slug: string;
                            }[];
                            marketType?: {
                                id: number;
                                name: string;
                                count: number;
                                key: string;
                            }[];
                            /** @description Additional match metadata from provider */
                            matchInfo?: {
                                /**
                                 * @description Match venue or location
                                 * @example Old Trafford, Manchester
                                 */
                                location?: string;
                                /**
                                 * @description Tournament stage
                                 * @example Semi Final
                                 */
                                stage?: string;
                                /**
                                 * @description Match format
                                 * @example Regular Time
                                 */
                                format?: string;
                            };
                            /** @description Live scoring context; present only when match is live */
                            scoreContext?: {
                                /**
                                 * @description Current period number
                                 * @example 2
                                 */
                                currentPeriod?: number;
                                /**
                                 * @description Stage live status
                                 * @example LIVE
                                 */
                                stageLiveStatus?: string;
                                /**
                                 * @description Current period string
                                 * @example 2nd Half
                                 */
                                currentPeriodString?: string;
                                /** @description Full score */
                                fullScore?: {
                                    /**
                                     * @description Home team full score
                                     * @example 2
                                     */
                                    home?: number;
                                    /**
                                     * @description Home team full score
                                     * @example 2
                                     */
                                    away?: number;
                                };
                                /**
                                 * @description Additional live match information
                                 * @example Match in progress
                                 */
                                info?: string;
                                /**
                                 * @description Current period (used in cricket)
                                 * @example 1
                                 */
                                period?: number;
                                /**
                                 * @description Scores per period
                                 * @example [
                                 *       {
                                 *         "Key": 1,
                                 *         "Value": {
                                 *           "NF": "1st Half",
                                 *           "S1": 1,
                                 *           "S2": 0
                                 *         }
                                 *       }
                                 *     ]
                                 */
                                periodScores?: {
                                    /**
                                     * @description Period key
                                     * @example 1
                                     */
                                    Key: number;
                                    Value: {
                                        /**
                                         * @description Normalized period label
                                         * @example HT
                                         */
                                        NF: string;
                                        /**
                                         * @description Home score for this period
                                         * @example 1
                                         */
                                        S1?: number;
                                        /**
                                         * @description Away score for this period
                                         * @example 0
                                         */
                                        S2?: number;
                                    };
                                }[];
                                setScore?: unknown;
                                /**
                                 * @description Timeout remaining (seconds)
                                 * @example 60
                                 */
                                timeoutRemaining?: number;
                                /**
                                 * @description Match time elapsed in seconds
                                 * @example 3420
                                 */
                                timeSeconds?: number;
                                /** @description Match statistics */
                                matchStatistics?: {
                                    /**
                                     * @description Statistics group key
                                     * @example 1
                                     */
                                    Key: number;
                                    Value: {
                                        /**
                                         * @description Statistic identifier
                                         * @example 101
                                         */
                                        ID: number;
                                        /**
                                         * @description Statistic name
                                         * @example Possession
                                         */
                                        N: string;
                                        /**
                                         * @description Home team value
                                         * @example 55%
                                         */
                                        S1: string;
                                        /**
                                         * @description Away team value
                                         * @example 45%
                                         */
                                        S2: string;
                                    }[];
                                }[];
                            };
                            /**
                             * @description SEO-friendly match slug
                             * @example manchester-united-vs-liverpool
                             */
                            slug: string;
                        }[];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        issues: {
                            path: string[];
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getGame: {
        parameters: {
            query?: {
                /** @description Response language (en, bn, hi, etc.) */
                locale?: "en" | "bn" | "hi";
                /** @description Market type filter */
                marketType?: "all_markets" | "popular" | "total" | "handicap" | "players" | "goals" | "intervals" | "other" | "points" | "games" | "result_plus_total" | "asian_markets" | "period" | "special";
            };
            header?: never;
            path: {
                /** @description Filter sports by event status */
                status: "live" | "upcoming";
                /** @description Unique identifier for the sport (e.g., 'football', 'cricket') */
                sport: string;
                /** @description Unique identifier for the league (e.g., '2796379-indonesia-liga-4') */
                league: string;
                /** @description Unique identifier for the event (e.g., '683886685-adelaide-united-vs-central-coast-mariners') */
                game: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game event details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /**
                         * Format: uuid
                         * @example 6f8a7c3e-1f2a-4d8e-b9a1-9c3b6a2c8f11
                         */
                        requestId: string;
                        data: {
                            /**
                             * @description Match identifier
                             * @example 987654
                             */
                            id: number | null;
                            /**
                             * @description Category identifier
                             * @example 4353456
                             */
                            ci?: number | null;
                            /** @description Match teams (home vs away) */
                            team: {
                                /**
                                 * @description Home team
                                 * @example {
                                 *       "id": 12345,
                                 *       "name": "Manchester United",
                                 *       "slug": "manchester-united",
                                 *       "countryId": 44,
                                 *       "logo": "https://cdn.example.com/teams/manchester-united.png"
                                 *     }
                                 */
                                home: {
                                    /**
                                     * @description Unique team identifier
                                     * @example 12345
                                     */
                                    id: number;
                                    /**
                                     * @description Team display name
                                     * @example Manchester United
                                     */
                                    name: string;
                                    /**
                                     * @description URL-friendly team identifier
                                     * @example manchester-united
                                     */
                                    slug: string;
                                    /**
                                     * @description Country identifier where the team is registered
                                     * @example 44
                                     */
                                    countryId: number;
                                    /**
                                     * @description Team logo URL
                                     * @example https://cdn.example.com/teams/manchester-united.png
                                     */
                                    logo?: string | null;
                                };
                                /**
                                 * @description Away team
                                 * @example {
                                 *       "id": 67890,
                                 *       "name": "Liverpool",
                                 *       "slug": "liverpool",
                                 *       "countryId": 44,
                                 *       "logo": "https://cdn.example.com/teams/liverpool.png"
                                 *     }
                                 */
                                away: {
                                    /**
                                     * @description Unique team identifier
                                     * @example 12345
                                     */
                                    id: number;
                                    /**
                                     * @description Team display name
                                     * @example Manchester United
                                     */
                                    name: string;
                                    /**
                                     * @description URL-friendly team identifier
                                     * @example manchester-united
                                     */
                                    slug: string;
                                    /**
                                     * @description Country identifier where the team is registered
                                     * @example 44
                                     */
                                    countryId: number;
                                    /**
                                     * @description Team logo URL
                                     * @example https://cdn.example.com/teams/manchester-united.png
                                     */
                                    logo?: string | null;
                                };
                            };
                            /**
                             * @description League information
                             * @example {
                             *       "id": 1,
                             *       "name": "Premier League",
                             *       "slug": "premier-league"
                             *     }
                             */
                            league: {
                                /**
                                 * @description Unique league identifier
                                 * @example 1
                                 */
                                id: number;
                                /**
                                 * @description League display name
                                 * @example Premier League
                                 */
                                name: string;
                                /**
                                 * @description URL-friendly league identifier
                                 * @example premier-league
                                 */
                                slug: string;
                            };
                            /**
                             * @description Country information
                             * @example {
                             *       "id": 44,
                             *       "name": "England"
                             *     }
                             */
                            country: {
                                /**
                                 * @description Unique country identifier
                                 * @example 44
                                 */
                                id: number;
                                /**
                                 * @description Country name
                                 * @example England
                                 */
                                name: string;
                            };
                            /**
                             * @description Match status
                             * @example live
                             * @enum {string}
                             */
                            status: "live" | "upcoming";
                            /**
                             * @description Unix timestamp (UTC)
                             * @example 1768651200
                             */
                            startTime: number;
                            /**
                             * @description event count
                             * @example 134
                             */
                            ec: number;
                            sport: {
                                /**
                                 * @description Unique sport identifier
                                 * @example 1
                                 */
                                id: number;
                                /**
                                 * @description Sport display name
                                 * @example Football
                                 */
                                name: string;
                                /**
                                 * @description URL-friendly sport identifier
                                 * @example football
                                 */
                                slug: string;
                            };
                            gameTypeId?: number;
                            period?: number;
                            periodName: string;
                            /**
                             * @description Transformed GE markets
                             * @example [
                             *       {
                             *         "id": 6,
                             *         "name": "Total Goals",
                             *         "gs": 1,
                             *         "outcomes": [
                             *           [
                             *             {
                             *               "id": 83,
                             *               "name": "(2.5) Over",
                             *               "coefficient": 1.9,
                             *               "suspended": false,
                             *               "point": 2.5
                             *             },
                             *             {
                             *               "id": 84,
                             *               "name": "(2.5) Under",
                             *               "coefficient": 1.9,
                             *               "suspended": false,
                             *               "point": 2.5
                             *             }
                             *           ]
                             *         ]
                             *       }
                             *     ]
                             */
                            markets?: {
                                /**
                                 * @description Market id
                                 * @example 6
                                 */
                                id: number;
                                /**
                                 * @description Localized market name
                                 * @example Total Goals
                                 */
                                name: string;
                                /**
                                 * @description Market game status
                                 * @example 1
                                 */
                                gs: number;
                                /**
                                 * @description Grouped outcomes (2D array)
                                 * @example [
                                 *       [
                                 *         {
                                 *           "id": 83,
                                 *           "name": "(2.5) Over",
                                 *           "coefficient": 1.9,
                                 *           "suspended": false,
                                 *           "point": 2.5
                                 *         },
                                 *         {
                                 *           "id": 84,
                                 *           "name": "(2.5) Under",
                                 *           "coefficient": 1.9,
                                 *           "suspended": false,
                                 *           "point": 2.5
                                 *         }
                                 *       ]
                                 *     ]
                                 */
                                outcomes: {
                                    /**
                                     * @description Outcome id
                                     * @example 83
                                     */
                                    id: number;
                                    /**
                                     * @description Localized outcome name
                                     * @example (2.5) Over
                                     */
                                    name: string;
                                    /**
                                     * @description Odds coefficient
                                     * @example 1.9
                                     */
                                    coefficient: number;
                                    /**
                                     * @description Outcome suspended status
                                     * @example false
                                     */
                                    suspended?: boolean;
                                    /**
                                     * @description Handicap / line value
                                     * @example 2.5
                                     */
                                    point?: number;
                                    /** @description Player/participant info (if applicable) */
                                    pl?: {
                                        /**
                                         * @description Player/participant id
                                         * @example 1
                                         */
                                        I: number;
                                        /**
                                         * @description Player/participant name
                                         * @example Player Name
                                         */
                                        N: string;
                                    };
                                }[][];
                            }[];
                            groups?: {
                                id: number;
                                name: string;
                                slug: string;
                            }[];
                            marketType?: {
                                id: number;
                                name: string;
                                count: number;
                                key: string;
                            }[];
                            /** @description Additional match metadata from provider */
                            matchInfo?: {
                                /**
                                 * @description Match venue or location
                                 * @example Old Trafford, Manchester
                                 */
                                location?: string;
                                /**
                                 * @description Tournament stage
                                 * @example Semi Final
                                 */
                                stage?: string;
                                /**
                                 * @description Match format
                                 * @example Regular Time
                                 */
                                format?: string;
                            };
                            /** @description Live scoring context; present only when match is live */
                            scoreContext?: {
                                /**
                                 * @description Current period number
                                 * @example 2
                                 */
                                currentPeriod?: number;
                                /**
                                 * @description Stage live status
                                 * @example LIVE
                                 */
                                stageLiveStatus?: string;
                                /**
                                 * @description Current period string
                                 * @example 2nd Half
                                 */
                                currentPeriodString?: string;
                                /** @description Full score */
                                fullScore?: {
                                    /**
                                     * @description Home team full score
                                     * @example 2
                                     */
                                    home?: number;
                                    /**
                                     * @description Home team full score
                                     * @example 2
                                     */
                                    away?: number;
                                };
                                /**
                                 * @description Additional live match information
                                 * @example Match in progress
                                 */
                                info?: string;
                                /**
                                 * @description Current period (used in cricket)
                                 * @example 1
                                 */
                                period?: number;
                                /**
                                 * @description Scores per period
                                 * @example [
                                 *       {
                                 *         "Key": 1,
                                 *         "Value": {
                                 *           "NF": "1st Half",
                                 *           "S1": 1,
                                 *           "S2": 0
                                 *         }
                                 *       }
                                 *     ]
                                 */
                                periodScores?: {
                                    /**
                                     * @description Period key
                                     * @example 1
                                     */
                                    Key: number;
                                    Value: {
                                        /**
                                         * @description Normalized period label
                                         * @example HT
                                         */
                                        NF: string;
                                        /**
                                         * @description Home score for this period
                                         * @example 1
                                         */
                                        S1?: number;
                                        /**
                                         * @description Away score for this period
                                         * @example 0
                                         */
                                        S2?: number;
                                    };
                                }[];
                                setScore?: unknown;
                                /**
                                 * @description Timeout remaining (seconds)
                                 * @example 60
                                 */
                                timeoutRemaining?: number;
                                /**
                                 * @description Match time elapsed in seconds
                                 * @example 3420
                                 */
                                timeSeconds?: number;
                                /** @description Match statistics */
                                matchStatistics?: {
                                    /**
                                     * @description Statistics group key
                                     * @example 1
                                     */
                                    Key: number;
                                    Value: {
                                        /**
                                         * @description Statistic identifier
                                         * @example 101
                                         */
                                        ID: number;
                                        /**
                                         * @description Statistic name
                                         * @example Possession
                                         */
                                        N: string;
                                        /**
                                         * @description Home team value
                                         * @example 55%
                                         */
                                        S1: string;
                                        /**
                                         * @description Away team value
                                         * @example 45%
                                         */
                                        S2: string;
                                    }[];
                                }[];
                            };
                            /**
                             * @description SEO-friendly match slug
                             * @example manchester-united-vs-liverpool
                             */
                            slug: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        issues: {
                            path: string[];
                            message: string;
                        }[];
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
}
